// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB50-y_06nCyXBWlSIYh64cJ6ya8rbl0OY',
    appId: '1:709946068420:web:71c6d0f03b1143fc0d6891',
    messagingSenderId: '709946068420',
    projectId: 'flutter-app-8f80b',
    authDomain: 'flutter-app-8f80b.firebaseapp.com',
    storageBucket: 'flutter-app-8f80b.firebasestorage.app',
    measurementId: 'G-RVB698CM1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACKoc-iIpT1GmeeO4egqYjxdnhYK3hUcM',
    appId: '1:709946068420:android:6d64eb981ae880f00d6891',
    messagingSenderId: '709946068420',
    projectId: 'flutter-app-8f80b',
    storageBucket: 'flutter-app-8f80b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ-Kov8ql35hBzeuvaOKqWjVRFV91SAM8',
    appId: '1:709946068420:ios:9a4bc0e515e94cab0d6891',
    messagingSenderId: '709946068420',
    projectId: 'flutter-app-8f80b',
    storageBucket: 'flutter-app-8f80b.firebasestorage.app',
    androidClientId: '709946068420-08ba156bukm7puv4ervsj2md0s159l4j.apps.googleusercontent.com',
    iosClientId: '709946068420-jfe20bungnd27lqfsaihunk9tms31vs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDevQuiz1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ-Kov8ql35hBzeuvaOKqWjVRFV91SAM8',
    appId: '1:709946068420:ios:9a4bc0e515e94cab0d6891',
    messagingSenderId: '709946068420',
    projectId: 'flutter-app-8f80b',
    storageBucket: 'flutter-app-8f80b.firebasestorage.app',
    androidClientId: '709946068420-08ba156bukm7puv4ervsj2md0s159l4j.apps.googleusercontent.com',
    iosClientId: '709946068420-jfe20bungnd27lqfsaihunk9tms31vs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDevQuiz1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB50-y_06nCyXBWlSIYh64cJ6ya8rbl0OY',
    appId: '1:709946068420:web:131ff3bd4781e7cf0d6891',
    messagingSenderId: '709946068420',
    projectId: 'flutter-app-8f80b',
    authDomain: 'flutter-app-8f80b.firebaseapp.com',
    storageBucket: 'flutter-app-8f80b.firebasestorage.app',
    measurementId: 'G-VMHZ374G4E',
  );
}
